#%RAML 1.0
---

title: Customs Declarations Information
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/xml

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Status and roadmap
    content: !include docs/api-status-and-roadmap.md
  - title: Data availability
    content: !include docs/data-availability-and-status.md
  - title: Authorisation
    content: !include docs/authorisation.md
  - title: Errors
    content: !include docs/errors.md
  - title: Testing
    content: !include docs/testing.md
  - title: XML Schemas
    content: !include docs/schema.md

/customs/declarations-information:
  /mrn:
    /{mrn}:
      uriParameters:
        mrn:
          description: |
            Movement Reference Number

            Must be a URL encoded string up to 35 characters long.
          type: string
          example: "20GB52P19SNIHX8PA6"
      /status:
        get:
          displayName: Get the status of a declaration by MRN
          description: Get the status of a declaration with the given MRN.
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.2.0+xml
            X-Badge-Identifier:
              description: |
                Represents the end-user who is interacting with the subscribed application.

                CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                Must be 6 to 12 characters, consisting of any combination of numeric digits and/or upper-case letters.
              type: string
              required: false
              example: ABC123
            X-Submitter-Identifier:
              description: |
                The EORI associated with the originating owner of the declaration.

                CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                Must have a maximum length of 17 characters, consisting of any combination of numeric digits and/or letters.
              type: string
              required: false
              example: GB123456789000
          (annotations.scope): "write:customs-declarations-information"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declarations-information" ] } ]
          responses:
            200:
              body:
                application/xml:
                  description: Successful response payload
                  type: !include schemas/wco/declaration/DeclarationInformationRetrievalStatusResponse.xsd
                  example: !include examples/example_messages/Trade%20Test%2012.3%20Sample%20Messages/TT_IM01c/TT_IM01c_DIS%20Status%20API%20Response_v1.1.xml

  /ducr:
    /{ducr}:
      uriParameters:
        ducr:
          description: |
             Declaration Unique Consignment Reference

             Must be a URL encoded string up to 70 characters long.
          type: string
          example: "8GB796458895018-G8536C"
      /status:
        get:
          displayName: Get the status of a declaration by DUCR
          description: Get the status of a declaration with the given DUCR.
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.1.0+xml
            X-Badge-Identifier:
              description: |
                Represents the end-user who is interacting with the subscribed application.

                CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                Must be 6 to 12 characters, consisting of any combination of numeric digits and/or upper-case letters.
              type: string
              required: false
              example: ABC123
            X-Submitter-Identifier:
              description: |
                The EORI associated with the originating owner of the declaration.

                CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                Must have a maximum length of 17 characters, consisting of any combination of numeric digits and/or letters.
              type: string
              required: false
              example: GB123456789000
          (annotations.scope): "write:customs-declarations-information"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declarations-information" ] } ]
          responses:
            200:
              body:
                application/xml:
                  description: Successful response payload
                  type: !include schemas/wco/declaration/DeclarationInformationRetrievalStatusResponse.xsd
                  example: !include examples/declarationInformationRetrievalDucrStatusResponseExample.xml

  /ucr:
    /{ucr}:
      uriParameters:
        ucr:
          description: |
            Unique Consignment Reference

            Must be a URL encoded string up to 35 characters long.
          type: string
          example: "9GB010969918000-5A8BD3F"
      /status:
        get:
          displayName: Get the status of a declaration by UCR
          description: Get the status of a declaration with the given UCR.
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.1.0+xml
            X-Badge-Identifier:
              description: |
                Represents the end-user who is interacting with the subscribed application.

                CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                Must be 6 to 12 characters, consisting of any combination of numeric digits and/or upper-case letters.
              type: string
              required: false
              example: ABC123
            X-Submitter-Identifier:
              description: |
                The EORI associated with the originating owner of the declaration.

                CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                Must have a maximum length of 17 characters, consisting of any combination of numeric digits and/or letters.
              type: string
              required: false
              example: GB123456789000
          (annotations.scope): "write:customs-declarations-information"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declarations-information" ] } ]
          responses:
            200:
              body:
                application/xml:
                  description: Successful response payload
                  type: !include schemas/wco/declaration/DeclarationInformationRetrievalStatusResponse.xsd
                  example: !include examples/declarationInformationRetrievalUcrStatusResponseExample.xml

  /inventory-reference:
    /{inventoryReference}:
      uriParameters:
        inventoryReference:
          description: |
             Inventory Reference

             Must be a URL encoded string up to 70 characters long. Spaces are permitted.
          type: string
          example: "GB%2F1234-%3A3333HZ"
      /status:
        get:
          displayName: Get the status of a declaration by Inventory Reference
          description: Get the status of a declaration with the given Inventory Reference.
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.1.0+xml
            X-Badge-Identifier:
              description: |
                 Represents the end-user who is interacting with the subscribed application.

                 CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                 Must be 6 to 12 characters, consisting of any combination of numeric digits and/or upper-case letters.
              type: string
              required: false
              example: ABC123
            X-Submitter-Identifier:
              description: |
                 The EORI associated with the originating owner of the declaration.

                 CSPs must have an X-Badge-Identifier or X-Submitter-Identifier.

                 Must have a maximum length of 17 characters, consisting of any combination of numeric digits and/or letters.
              type: string
              required: false
              example: GB123456789000
          (annotations.scope): "write:customs-declarations-information"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declarations-information" ] } ]
          responses:
            200:
              body:
                application/xml:
                  description: Successful response payload
                  type: !include schemas/wco/declaration/DeclarationInformationRetrievalStatusResponse.xsd
                  example: !include examples/declarationInformationRetrievalIrStatusResponseExample.xml
